name: clang-format Check
on: [push, pull_request, workflow_dispatch]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - check: "lib/compiler"
          - check: "lib/ffi"
          - check: "lib/kernels"
          - check: "lib/op-attrs"
          - check: "lib/pcg"
          - check: "lib/runtime"
          - check: "lib/substitutions"
          - check: "lib/utils"
          - check: "tests"
          - check: "examples"
          - check: "bindings"
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: lockshaw/clang-format-action@v4.11.0-flexflow
        with:
          clang-format-version: "16"
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
