name: "docker-build"
on:
  pull_request:
    paths-ignore:
      - "docker/**"
      - "!docker/README.md"
      - ".github/workflows/docker-build.yml"
  workflow_dispatch:

# Cancel outdated workflows if they are still running
concurrency:
  group: docker-build-skip-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker-build-rocm:
    name: Build and Install FlexFlow in a Docker Container (ROCm backend)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hip_version: ["5.3", "5.4", "5.5", "5.6"]
      fail-fast: false
    steps:
      - run: 'echo "No docker-build required"'
  
  docker-build-cuda:
    name: Build and Install FlexFlow in a Docker Container (CUDA backend)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda_version: ["11.1", "11.6", "11.7", "11.8", "12.0", "12.1", "12.2"]
      fail-fast: false
    steps:
      - run: 'echo "No docker-build required"'
